version: "3"  
services:  
  prometheus:
       image: prom/prometheus:latest
       ports:
       - 5000:5000
       volumes:
       - "./prometheus.yml:/etc/prometheus/prometheus.yml"

  app:
      container_name: app
      build: ./my_flask_app/.
      ports:
      - 9090:9090
      volumes:
      - "./my_flask_app/app.py:/app.py"
