apiVersion: v1
kind: Pod
metadata:
  name: $PODNAME
  labels:
    testlabel: test
spec:
  # hostIPC: true
  volumes:
    - name: sumoconfig
      hostPath:
        path: $CONFIGPATH
        type: Directory
  containers:
    - name: webgui
      image: crltp-novnc
      # command: [ "tail", "-f", "/dev/null" ]
      # command: ["sh", "-c", "vncserver -geometry 1024x768 :1 -noshared -X11ShmDisabled"]
      # command: [ "/usr/bin/vncserver", "-geometry", "1024x768", ":1", "-noshared", "-X11ShmDisabled" ]
      env:
        #- name: QT_X11_NO_MITSHM 
        #  value: 1
        - name: DISPLAY_X
          value: $DISPLAY_X
        - name: DISPLAY_Y
          value: $DISPLAY_Y
        - name: VNC_PW
          value: admin12
      ports:
        - name: novnc-port
          containerPort: 8080
          hostPort: $SUMO_NOVNC_PORT
          protocol: TCP
          
    - name: sumoct
      restartPolicy: Always
      image: crltp-sumo
      env:
        #- name: QT_X11_NO_MITSHM 
        #  value: 1
        - name: DISPLAY
          value: 127.0.0.1:1
        - name: CONFIG
          value: $CONFIG
        - name: START
          value: $START
        - name: DELAY
          value: $DELAY
        - name: SUMO_HOME
          value: /usr/share/sumo
      ports:
        - name: sumo-port
          containerPort: $RPORT
          hostPort: $RPORT
          protocol: TCP
      volumeMounts:
        - name: sumoconfig
          mountPath: /sumo

    - name: simbackend
      image: crltp-simbackend
      env:
        - name: SIM_PORT
          value: 8813
        - name: SIM_HOST
          value: localhost
        - name: SIM_LABEL
          value: main
        - name: DELAY
          value: $DELAY
        - name: SIM_API_PORT
          value: $SIM_API_PORT