apiVersion: v1
kind: Pod
metadata:
  name: $PODNAME
  labels:
    testlabel: test
spec:
  # volumes:
  #   - name: sumoconfig
  #     hostPath:
  #       path: $CONFIGPATH
  #       type: Directory
  containers:
  
    # SimYellow declaration
    - name: simyellow
      image: crltp-simyellow
      env:
        - name: SIM_LABEL
          value: main
        - name: SIM_API_PORT
          value: $SIM_API_PORT
        - name: AMT_API_PORT
          value: $AMT_API_PORT